### ISSUE TITLE
Create Slider.js component for CardsColumns.js on mobile

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#102]
As a user, I want to see the cards from the `CardsComponent.js` displayed in a slider on mobile and tablets (screens <  769px) as per [this reference website](https://thecozyshop.com/) (and attached)

![carousel-example-mobile](https://user-images.githubusercontent.com/20016897/170416708-7c63e2af-ed78-4815-b4c2-0d56c7580d4a.png)

![carousel-example-tablet](https://user-images.githubusercontent.com/20016897/170416711-d1160f5e-eabd-4b93-8d8b-9d2d164b8566.png)

---

Once you have the most up-to-date `master` branch locally (git pull from your local master branch), create a new branch `git checkout -b feature/implement-slider` to get started. Check out our [Wikipedia page](https://github.com/Web-Dev-Path/web-dev-path/wiki/Getting-Started) to learn more about that process.

**Please, keep in mind that once you assign this task to yourself you'll need to complete it in 10 days.**

**_Approach suggestion:_**

[Use the component from this Flickity React library](https://www.npmjs.com/package/react-flickity-component)

**_Acceptance Criteria:_**

- Ensure the CardsColumns.js is displayed in a slider on tablets and mobile as per [the reference website](https://thecozyshop.com/) on the Homepage with no console errors.
- Test the feature in many screen sizes, you can use the Inspect tool for that.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by luke-buttifant** [comment]
Hey, I would like to implement this!
