### ISSUE TITLE
Update Footer Design

### ISSUE THREAD

**Issue by kimbercash** [Web-Dev-Path/web-dev-path#111]
Added the updated footer to hi-fi mockups in Figma, including mobile version. 

7/4/2022 - Swapped LinkedIn icon for YouTube & updated on hi-fi mockups

**Comment by kimbercash** [comment]
Replace LinkedIn logo with YouTube

**Comment by mariana-caldas** [comment]
It looks great, @kimbercash !
I'm creating an issue for the devs to revamp the footer now. Thanks so much! 🚀
