### ISSUE TITLE
Update "About Us" page

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#117]
I think we just need to update some details to finalize [the new](https://www.figma.com/file/OBodwq9110eMa0kTSPiCBD/WDP---Kim-Copy?node-id=0%3A1) "About Us" page, @kimbercash 

1. Can we just adjust the margins on the section "Our Goals", pls?
![image](https://user-images.githubusercontent.com/20016897/180097417-abb46d0f-47f8-49b3-bf09-43df8e243c74.png)

2. Can we use [our project baby blue background](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=80%3A479) with our dark grey for the fonts on this "Wanna learn more section"?
![image](https://user-images.githubusercontent.com/20016897/180097528-bfdca44d-cc86-4ccd-95c8-d5b42b8d88b7.png)

3. Can we use the # symbol here instead of the [ ] on this last final section? I think the [] would make more sense in the section "Our background", the first one.
![image](https://user-images.githubusercontent.com/20016897/180097715-1302e306-c17a-4a6a-814b-8f5c132ba7d7.png)

Please let me know your thoughts, @kimbercash ! Thanks!

**Comment by kimbercash** [comment]
- [ ] Adjust margins on "Our Goals" section
- [ ] "Wanna Learn More" - baby blue background, dark gray font
- [ ] Use # symbol instead of [ ] on final section

**Comment by kimbercash** [comment]
@mariana-caldas I've saved all of these updates [here ](https://www.figma.com/file/OBodwq9110eMa0kTSPiCBD/WDP---Kim-Copy?node-id=2%3A465) and also updated a couple minor spacing discrepancies. Let me know what you think! :)

Another thing I noticed was that the "}" symbol in the baby blue section is graphite (#292929), while all the other symbols are the Web Dev Branding Blue color. Was this on purpose or do you want me to change that symbol to match the rest?

![image](https://user-images.githubusercontent.com/8846386/181237812-474e991e-3e9e-4d55-b659-d04d3cae44ef.png)

**Comment by mariana-caldas** [comment]
> @mariana-caldas I've saved all of these updates [here ](https://www.figma.com/file/OBodwq9110eMa0kTSPiCBD/WDP---Kim-Copy?node-id=2%3A465) and also fixed a couple minor spacing discrepancies. Let me know what you think! :)
> 
> Another thing I noticed was that the "}" symbol in the baby blue section is graphite (#292929), while all the other symbols are the Web Dev Branding Blue color. Was this on purpose or do you want me to change that symbol to match the rest?
> 
> ![image](https://user-images.githubusercontent.com/8846386/181237812-474e991e-3e9e-4d55-b659-d04d3cae44ef.png)

Good point on that symbol color! 
Yeah, I think we can keep it grey just to be consistent with its own section for now. 
Such a great job, @kimbercash ! I think it is ready to copy over to the originals as well whenever you can.
Thanks so much! 🚀

**Comment by kimbercash** [comment]
@mariana-caldas great! I copied it over to the originals. I titled the frame "About Page - v2" but didn't remove the other ones just in case... do you think that will be too confusing?

**Comment by mariana-caldas** [comment]
> @mariana-caldas great! I copied it over to the originals. I titled the frame "About Page - v2" but didn't remove the other ones just in case... do you think that will be too confusing?

It's perfect, @kimbercash ! Thanks so much!
