### ISSUE TITLE
Improve Lighthouse scores

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#118]
We've realized that we could improve our platform Lighthouse scores, especially the Performance, to try reaching the "green" marks, representing 90 points in each segment. This is how our marks are so far:

![web-dev-path-lighthouse-24-7-22](https://user-images.githubusercontent.com/20016897/180664758-d199894d-6393-4ea8-8524-42ab9d078303.png)

**Technical details:**

Once you're a team project member and carefully read [our process](https://github.com/Web-Dev-Path/web-dev-path/wiki/Getting-Started), git pull from main and create a new branch `chore/improve-lighthouse-scores` where you are committing the changes to and submitting your Pull Request from.

We probably need to tackle these points:

* Image optimizations: please use a tool such as https://squoosh.app/ to convert the images into .webp format
* Please add width/height to the navbar logo
* Please check if there is a better way to load the Google Fonts and reCaptcha ( I think we're missing something here).
* Please add a `robots.txt` file to the project -> https://coderrocketfuel.com/article/add-a-robots-txt-file-to-your-next-js-website / https://postsrc.com/code-snippets/how-to-add-a-robotstxt-file-to-a-nextjs-project

_Please remember that once you assign this task to yourself, you'll need to complete it in 15 days._

**Acceptance criteria:**

* After ensuring the scores have improved, test the site in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
* Update the CHANGELOG.md file.

**Comment by vmcodes** [comment]
@mariana-caldas  I made some updates that I'll push when I can, but I got much higher scores from where I'm located. I've noticed this same issue with a friend who is also outside the US.

![Screenshot from 2022-07-24 21-32-50](https://user-images.githubusercontent.com/30095385/180677446-561e46b8-93d1-4c0c-9741-7328fb730bb9.png)

**Comment by cherylli** [comment]
Not sure how they calculate the score. Here's what I got but every time I run the report it shows different scores.
I can understand performance might depend on the location and distance to the server but SEO score shouldn't change?
[![](https://i.imgur.com/0wLv3IXm.jpg)](https://i.imgur.com/0wLv3IX.png)

**Comment by vmcodes** [comment]
Cool! Maybe the CDN servers aren't distributed very evenly. While not the best news, at least we're seeing better results overall.
