### ISSUE TITLE
Update About Us first section

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#121]
We need to update the About Us page first section to match [the updated design files, **About Page v2**](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=1129%3A3171) (and below)

![image](https://user-images.githubusercontent.com/20016897/182289364-a0994443-e789-4d68-ac30-b0d61c60bbab.png)

**Technical details:**

- Once you're a team project member and carefully read [our process](https://github.com/Web-Dev-Path/web-dev-path/wiki/Getting-Started), `git pull` from `main` and create a new branch `chore/update-about-us-first-section` where you are committing the changes to and submitting your Pull Request from.
- Please use the TwoColumn component for that -> https://github.com/Web-Dev-Path/web-dev-path/blob/main/components/containers/TwoColumn.js

_Please remember that once you assign this task to yourself, you'll need to complete it in 10 days._

**Acceptance criteria:**

- Test the feature in many screen sizes, you can use the Inspect tool for that.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by klezi10** [comment]
Just confirming that the first section is the yellow "our background" section, is that right @mariana-caldas ?

**Comment by mariana-caldas** [comment]
> Just confirming that the first section is the yellow "our background" section, is that right @mariana-caldas ?

All the current first section about us content will be replaced with those new 3 sections, @klezi10 . We're basically dividing that content a little bit more into smaller blocks of text. Does that make sense? Thanks for confirming! 🙌🏼
