### ISSUE TITLE
Add "Wanna learn more?" and "How to get started?" sections to the About Us page

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#125]
We need to add the **"Wanna learn more?"** and **"How to get started?"** sections to the About Us page by considering [the updated design files, **About Page v2**](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=1129%3A3171) (and below)

![image](https://user-images.githubusercontent.com/20016897/185812943-cc84a934-082c-4c7e-9ad4-a30281d4f9b5.png)

**Technical details:**

- Please consider the PR https://github.com/Web-Dev-Path/web-dev-path/pull/124 is being coded so you can either wait for it to be merged or consider you are pulling some changes from that branch later before merging yours.

- Once you're a team project member and carefully read [our process](https://github.com/Web-Dev-Path/web-dev-path/wiki/Getting-Started), `git pull` from `main` and create a new branch `feature/wanna-learn-more` where you are committing the changes to and submitting your Pull Request from.

- The section "Wanna learn more?" can be a combination of the `TwoColumn` component https://github.com/Web-Dev-Path/web-dev-path/blob/main/components/containers/TwoColumn.js called twice. Those new component instances will need  `customClass` properties to be styled accordingly. Also, the two content columns that represent _"Junior Developers"_ and _"Experienced Developers"_ could be added by a new property called `secondTextColumn` which, when it exists, would render a second column with text (not image) to the component.

- Please use the `TwoColumn` component too to add the section "How to get started?". Please keep in mind that the component is already used in other instances so any styling change will be done under the specific styling class we see here:

![image](https://user-images.githubusercontent.com/20016897/183342865-8c55c00b-6ad0-4bf9-8222-ad05239d4298.png)

_Please remember that once you assign this task to yourself, you'll need to complete it in 10 days._

**Acceptance criteria:**

- Test the sections in many screen sizes, you can use the Inspect tool for that. 
- Please test if the new changes do not affect the other instances that are using the components on the homepage and about us.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
the close curly bracket in the figma design file is different from the rest of the files, is it correct? The colour is different with a drop shadow
