### ISSUE TITLE
Contact Us form (visual component without functionality)

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#126]
We need to add the `ContactUsForm` component, its decoration components, as well as the proper Hero content description (the one under "Contact Us" heading on the top right) form to the Contact Us page by considering [the design files](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=1129%3A3171) (and below)

The idea is only adding the visual part now since the form functionality that will make the messages to be sent to the project email will be implemented later after some discovery. **So this PR will not be merged to `main` since the email functionality will be added to the same branch created here.**

![contact-us-form](https://user-images.githubusercontent.com/20016897/185813851-76e49324-eae6-492a-892c-075d5c48e44a.png)

**Technical details:**

- Once you're a team project member and carefully read [our process](https://github.com/Web-Dev-Path/web-dev-path/wiki/Getting-Started), `git pull` from `main` and create a new branch `feature/contact-us-form-visual` where you are committing the changes to and submitting your Pull Request from. **This branch will not be merged to `main` since the email functionality will be added to the same branch created here.**

- The new component, `ContactUsForm`, will be placed under the first-page section and will be displayed absolutely (on the top) of the Hero component only on desktop. On mobile, it will occupy the first-page section. If possible, use the `ButtonLink` component to build it.

- The decoration components "{" and ":" will be hidden on mobile.

_Please remember that once you assign this task to yourself, you'll need to complete it in 15 days._

**Acceptance criteria:**

- Test the section and components in many screen sizes, you can use the Inspect tool for that. 
- Please test if the new changes added to the `Bracket` component do not affect the other homepage instance.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
Do we want to use something like react-hook-form?

**Comment by mariana-caldas** [comment]
> Do we want to use something like react-hook-form?

I think that's an excellent idea @cherylli !
It seems easier to validate the fields this way -> https://react-hook-form.com/get-started

**Comment by mariana-caldas** [comment]
Hey @klezi10 🚀 

Just passing by to mention that although the react-form-hook seems to be a nice way to implement the form and its field validations, I encourage you to learn doing that without a library as well. I found [this tutorial ](https://www.youtube.com/watch?v=EYpdEYK25Dc)pretty nice to get started.
Also, when implementing it, let's keep in mind how it's going to be integrated with [SendGrid ](https://www.freecodecamp.org/news/how-to-build-a-working-contact-form-with-sendgrid-and-next-js/)(take a look at the `handleValidation( )` ), the platform we're probably using to send the email. 🙌🏼

**Comment by klezi10** [comment]
Thank you @mariana-caldas I've already set up forms from scratch but I've been looking to try react-form-hook so I was pretty happy to see the opportunity here.
