### ISSUE TITLE
Discovery: Contact Us form functionality

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#127]
We need to implement the functionality to the `ContactUsForm` component rendered on the Contact Us page. To do that, we need to find out the best way of doing that. That's why this card is labeled as a `discovery` one since the initial goal is not implementing the functionality itself but researching and reporting approaches to do so.

This issue is related to #126, but it is not blocked by it, so it can be initiated immediately.

**Technical details:**

- By researching solutions such as "How to implement/create a contact form on Next.js", select some approaches that make sense to you, either tutorial blogs or videos, and add them to the comments by considering their pros and cons. Please watch and read carefully your suggestions trying to foresee any issues or questions your choices present.

_Please remember that once you assign this task to yourself, you'll need to complete it in 15 days._

**Acceptance criteria:**

- Add to the comments your approaches by considering their pros and cons.

**Comment by cherylli** [comment]
Assuming you want to send the contact form details to an email,
it seems using next.js serverless api routes and sendgrid is the standard

https://betterprogramming.pub/how-to-create-a-working-contact-form-in-next-js-459d1fc992ea
https://www.freecodecamp.org/news/how-to-build-a-working-contact-form-with-sendgrid-and-next-js/

the only variable is which email service to use

In this article, they use SendGrid, which is a popular service for this purpose, and they have a free tier with restrictions which mostly don't matter to us.

**Comment by mariana-caldas** [comment]
> Assuming you want to send the contact form details to an email, it seems using next.js serverless api routes and sendgrid is the standard
> 
> https://betterprogramming.pub/how-to-create-a-working-contact-form-in-next-js-459d1fc992ea https://www.freecodecamp.org/news/how-to-build-a-working-contact-form-with-sendgrid-and-next-js/
> 
> the only variable is which email service to use
> 
> In this article, they use SendGrid, which is a popular service for this purpose, and they have a free tier with restrictions which mostly don't matter to us.

Yep, we're sending the contact form details to an email and I like how straightforward this approach is, @cherylli ! 🚀 
I think I'll wait a few more days to see if someone else has another idea or foresee any problems and, then, I'll create a SendGrid account to get the API key we need! 🙌🏼
