### ISSUE TITLE
Implement Contact Us form functionality

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#135]
**What do we need to build or fix?**

We need to implement the functionality of the ContactUsForm component rendered on the Contact Us page.
After investigating the best approach on #127 , we decided to use SendGrid to add the functionality.

**Technical details**
- Start your branch from the [feature/contact-us-form-visual-2](https://github.com/Web-Dev-Path/web-dev-path/tree/feature/contact-us-form-visual-2), PR #134 . Once your PR is submitted, please close the #134 with a message explaining that PR is being finalized through yours.
- We're using the email [hello@webdevpath.co](mailto:hello@webdevpath.co)
- If you need to install any package, please do it with the default project package manager, `yarn`
- Please ping @mariana-caldas on Slack to get the SendGrid API key that will be added to the `.env` file under the new variable `SENDGRID_API_KEY`
- Also, please add the new variable placeholder to the .`env-template` file

**Approach suggestions**

https://betterprogramming.pub/how-to-create-a-working-contact-form-in-next-js-459d1fc992ea
https://www.freecodecamp.org/news/how-to-build-a-working-contact-form-with-sendgrid-and-next-js/

**Deadline**

Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
once then form is submitted, do we want to 
1. show an alert
2. redirect to another page, or
3. show a message somewhere near the form?

![image](https://user-images.githubusercontent.com/6191116/190884870-ec1b53cf-167f-42d5-834b-7ae54d00601d.png)
Do these error messages need to be easier to see? Maybe red or another colour? Took me a while to see them as a user 

Does checking the subcribe button do anything? Or just send true/false in the email message?

**Comment by mariana-caldas** [comment]
Hey @cherylli ! Thanks for the great questions 🚀 

1. Let's show the following message below the form as per the attached example "Your message was sent successfully. We'll answer you back soon, thanks!"

![image](https://user-images.githubusercontent.com/20016897/190885712-3f1e3c8f-1b36-44a0-a90c-f020b99dafc2.png)

2. That's a good point, @cherylli ! Because the background is blueish, can we try with the project yellow?

3. I had totally forgotten about this! Yes, when checked and on form submission, the email added should be added to our subscription list. So the Newsletter/MailChimp logic will have to be adapted as well.

**Comment by cherylli** [comment]
one more thing, we should add recaptcha like the newsletter form too right?
