### ISSUE TITLE
Add "Who we are" section to About Us page

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#137]
**What do we need to build or fix?**

By considering our [mockup guidelines](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/Web-Dev-Path_design?node-id=414%3A936), we need to add the "who we are" section to the about us page.

![image](https://user-images.githubusercontent.com/20016897/190952354-6e58fcb2-fac8-4001-ac09-67d183c49591.png)

**Technical details**

- From the most up-to-date ` main`, create a branch `feature/who-we-are-about-us` where to add the functionality.
- Please ping @mariana-caldas on Slack to get access to the member's folder whith all the content.

**Approach suggestions**

- Create a `Row.js` component that leverages [flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) where to add the members' cards. This new component will be children of `Container.js` to ensure width consistency along the platform.

- Create a `Member.js` component that will contain the following elements: image, name, role, linkedin, portfolio, and description. That information (elements) will be added to a JSON file that will populate the new component. Take a look at [this reference](https://github.com/Web-Dev-Path/web-dev-path/blob/main/components/containers/CardsColumns.js#L40), where the `titles` determine how many cards with a slider will be rendered since you'd need to do something similar on `about.js` page to render the members. Finally, add a check for the `portfolio` element or a `boolean` property `hasPortfolio` to the JSON as seen [here](https://github.com/Web-Dev-Path/web-dev-path/blob/main/utils/links.js#L14), so we can render conditionally the portfolio links.

**Deadline**

Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
I don't think we need a hasPortfolio property as we can just check if portfolio is empty/null/undefined while populating it like,

{profile.portfolio && <div>whatever</>}
