### ISSUE TITLE
Implement Search Bar functionality 

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#155]
**What do we need to build or fix?**

Currently, we have the [front-end search functionality](https://github.com/Web-Dev-Path/web-dev-path/blob/main/components/blog/SearchBar.js) and it is commented out on the [blog page](https://github.com/Web-Dev-Path/web-dev-path/blob/main/pages/blog/index.js#L18), we need to add the logic so that any user can search the blog posts data on that page.

**Technical details**
- Implement the functionality by considering the blog posts

**Approach suggestions**
 - On the blog `index.js`,  add the `revalidate` prop to the `getStaticProps` function to use the [Incremental Static Generation Approach
](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration)
- Then, by considering the `posts` object returned from the `getStaticProps` function, add the search logic. Suggested tutorials about the search logic implementation:
   https://www.youtube.com/watch?v=ZoayCCDHFiI / https://www.youtube.com/watch?v=lOIrlONj3So

**Deadline**

Please keep in mind that once you assign this task to yourself, you'll need to complete it in 20 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
I don't think the link is relavent is it's for a next.js "markdown blog" which is not what we have now. It has articles in the file system and we don't. We already have all the posts fetched (using SSR which I think we should switch to ISR), so we could just search in that posts array and display it using the BlogContainer component

**Comment by mariana-caldas** [comment]
> @mariana-caldas I don't think the link is relavent is it's for a next.js "markdown blog" which is not what we have now. It has articles in the file system and we don't. We already have all the posts fetched (using SSR which I think we should switch to ISR), so we could just search in that posts array and display it using the BlogContainer component

Great point, @cherylli , thanks! I've updated the issue with your idea 🥳 . However, just to clarify for everyone reading this is the future YOU DON'T have to follow anything suggested under "approach suggestions"; you may have a better way to tackle things so never limit yourself!

**Comment by cherylli** [comment]
@mariana-caldas I have a some questions regarding the search, 
1. is the search bar only in the blog main page?
2. should the result be displayed in the same page or redirect to a "Search result page"?

**Comment by cherylli** [comment]
@mariana-caldas, since there's not much specification in the design, do you want the search to work like this?
https://fem-entertainment-web-app.netlify.app/

if so, the search button will just be a decoration
