### ISSUE TITLE
Add XML Sitemap

### ISSUE THREAD

**Issue by vmcodes** [Web-Dev-Path/web-dev-path#167]
**What do we need to build or fix?**

Add a dynamic XML Sitemap to better help with search result indexing.
 
**Technical details**

Each page will be dynamically added to the sitemap for each build.
Sitemap with be located at https://www.webdevpath.co/sitemap.xml
Add sitemap.xml to robots.txt

**Approach suggestions**

Using 'getServerSideProps' as noted in the Next.js documentation
https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by mariana-caldas** [comment]
That sounds amazing, @vmcodes !
