### ISSUE TITLE
[Bug] "Who we are" section in "About" is not showing up in mobile view

### ISSUE THREAD

**Issue by cherylli** [Web-Dev-Path/web-dev-path#189]
**What do we need to build or fix?**
In mobile view (live and dev), "who we are" section is not showing up. Desktop version is fine.
I have tried this on my phone and PC browser (chrome and edge). The issue happens on PC is not 100% but it's 100% on my phone (chrome, firefox)

Is anyone else experiencing this?

**Technical details**
Scrolling down the page `https://www.webdevpath.co/about`

![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/5c34325e-9140-418b-a9cb-fab53d4212c2)
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/133a2eb0-2ed6-4eae-aa1e-773e2d975cda)
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/e0cb7d97-4634-40f7-adcb-e18a543db94e)
![image](https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/76366e72-9a87-4c1c-b1ec-2f0e6e24b38c)

**Approach suggestions**
No suggestion yet, I would like to confirm if anyone else getting this

**Deadline**
N/A

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by Satoshi-Sh** [comment]
Interesting. I got the same bug on mobile.  When I opened the About page with a desktop browser with shorter width, the profiles didn't get displayed as well. It has something to do with the window width.

I will let you know if I find the cause of this bug.

**Comment by cherylli** [comment]
Thanks for checking. I think it might be related to the styled-components conversion as it was definitely working before that. Maybe the mobile styles weren't ported properly.

**Comment by Satoshi-Sh** [comment]
I thought putting the issue number in the pull request description takes care of linking. Now I know how to link the issue. Thanks, Mariana!!
