### ISSUE TITLE
Discuss and Add License to the project

### ISSUE THREAD

**Issue by cherylli** [Web-Dev-Path/web-dev-path#195]
**What do we need to build or fix?**
We want to add a license to the project and need to pick one which suits us best.

**Technical details**
To add a license to a github project, we add `LICENSE.md` to the root of our repository. Github has a built-in feature to automatically create one for us after picking a license. 
[Github Docs-Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Approach suggestions**
1. Choose a License: https://choosealicense.com/
2. Here is a summary of some common licenses for opensource projects: 
https://choosealicense.com/licenses/
3. Here are the details of all the OSI Approved Licenses: https://opensource.org/licenses/
4. https://www.youtube.com/watch?v=5_n1PN0mWWQ&ab_channel=3-MinuteExplanation

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
I'm thinking GPLv3, depends on how restrictive we want to be?

**Comment by mariana-caldas** [comment]
> **What do we need to build or fix?** We want to add a license to the project and need to pick one which suits us best.
> 
> **Technical details** To add a license to a github project, we add `LICENSE.md` to the root of our repository. Github has a built-in feature to automatically create one for us after picking a license. [Github Docs-Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
> 
> **Approach suggestions**
> 
> 1. Choose a License: https://choosealicense.com/
> 2. Here is a summary of some common licenses for opensource projects:
>    https://choosealicense.com/licenses/
> 3. Here are the details of all the OSI Approved Licenses: https://opensource.org/licenses/
> 4. https://www.youtube.com/watch?v=5_n1PN0mWWQ&ab_channel=3-MinuteExplanation
> 
> **Deadline** Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.
> 
> **Acceptance criteria**
> 
> * Test the section and components in many screen sizes, you can use the Inspect tool for that.
> * Please test if the new changes added to the components do not affect the other instances.
> * Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
> * If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
> * Update the CHANGELOG.md file.

Thanks, Cheryl! Doing some research about them, but we don't want to be too restrictive.
Just clarifying that before implementing this we need to discuss here the best approach for us.
Will be back in a bit with some findings to help us to decide the best fit for us.

**Comment by mariana-caldas** [comment]
Hello everyone,

As we continue discussing the selection of an open-source license for our website project repository, it's important to weigh our choices against our project's goals, values, and our intention to monetize the project through [GitHub Sponsors](https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors). Here are three license options I'd consider:

**MIT License:**
The MIT License is a permissive license that encourages collaboration and contribution without imposing extensive restrictions. It aligns well with our goal of fostering a collaborative community, and it's compatible with GitHub Sponsors.

**Apache License 2.0:**
The Apache License 2.0 offers patent protection, clear documentation requirements, and permissive terms. This can provide legal security while still enabling collaboration and community growth. It's also compatible with GitHub Sponsors.

**GNU General Public License version 3 (GPLv3):**
GPLv3 is a strong copyleft license that ensures derivative works also remain open-source and shareable under the same terms. While it enforces collaboration, it might be more restrictive for potential contributors. However, it's still a valid option for GitHub Sponsors.

It's important to remember that our intention to monetize the project through GitHub Sponsors is aligned with all of these license options. Sponsors typically consider factors like community engagement, project goals, and values. While the license choice itself doesn't directly impact eligibility for GitHub Sponsors, permissive licenses (MIT, Apache) might align more naturally with potential sponsors' interests.

Looking forward to your input!

**Comment by cherylli** [comment]
I like GPLv3 more as it requires people to disclose source and state changes.

**Comment by mariana-caldas** [comment]
> I like GPLv3 more as it requires people to disclose source and state changes.

Me too, Cheryl. The only point to consider is that it may limit our possibilities of receiving donations through the GitHub Sponsors, one of the ways I'm considering to monetize our project.
