### ISSUE TITLE
404 Errors on Production Blog Page

### ISSUE THREAD

**Issue by Satoshi-Sh** [Web-Dev-Path/web-dev-path#213]
**What do we need to build or fix?**
There are 404 errors on the production blog page. It works fine locally.

**Technical details**
No errors show up on the browser console.

**Approach suggestions**
I'm not sure of the cause of this error yet.

**Screenshot**
![404_errors](https://github.com/Web-Dev-Path/web-dev-path/assets/73622805/c3a4eaa5-b063-4cfb-b9b3-c73324fb0f73)

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
Looks like some next generated files  in the _next folder.
But I don't know what those resources do, looks like the website is working fine
@mariana-caldas was there a build error/warning on netlify in the last build?

**Comment by mariana-caldas** [comment]
> Looks like some next generated files in the _next folder. But I don't know what those resources do, looks like the website is working fine @mariana-caldas was there a build error/warning on netlify in the last build?


Hey, @Satoshi-Sh and @cherylli !

Thanks for taking a look into it. We have no build errors/warnings, Cheryl, but I find it weird how the links to the tags are being formed. I mean, it's ending with the tag name + json. That may be causing the 404 because we don't have those files. 
Yep, this have to be solved , but does not block any other feature development for now. 🙌🏼

**Comment by Satoshi-Sh** [comment]
Resolved by upgrading Next.js to 14 in #228
