### ISSUE TITLE
Create the UI for the Single Blog Post page

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#214]
**What do we need to build or fix?**
We need to build a responsive single blog post page for our open-source website [Web Dev Path](https://www.webdevpath.co/). Currently, our blog page posts' cards' links redirect users to the [dev.to](https://dev.to/wdp) platform. The goal is to keep users on our website longer by creating a page UI with the following new sections: "Single Post Content," "Author Bio," and "Related Posts."

![single-blog-post](https://github.com/Web-Dev-Path/web-dev-path/assets/20016897/a540fb5f-ab21-4ac5-85dc-d54534bf0574)

**Technical details**

Create the UI for the single blog post page with the following sections:

_1. Single Post Content:_

- Display the blog post content.
- The post image should be optional.

_2. Author Bio:_

- Display the author's bio.
- The author image should be optional with a placeholder default (Figma file).
- Only the LinkedIn icon link is mandatory. If not provided, use the Web Dev Path LinkedIn group: [Web Dev Path LinkedIn](https://www.linkedin.com/company/web-dev-path).

_3. Related Posts:_

Display the first 5 similar posts by considering the post's tags.

**Approach suggestions**

- Reference the Figma mockup designed by @kimbercash . Ping @mariana-caldas  to get access to the Figma file.
- For design questions, please talk to @kimbercash  on our Slack channel #design-gate.
- _This task only includes the UI creation, not the current connection from the blog page, the redirection, or the URL link creation for the single posts. These will be handled in future tasks._
- Ensure the page is fully responsive by stacking elements when the screen width requires. Check the codebase for reference and consistency.

**Deadline**
_Please keep in mind that once you assign this task to yourself, you'll need to complete it in 30 days._

**Acceptance criteria**

- Test the section and components in many screen sizes; you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by cherylli** [comment]
I wrote this a while ago when working on all blog post page, in the bottom of the article it shows how to retrieve a single post

https://dev.to/cherylli/displaying-devto-articles-on-your-website-using-nextjs-1bbk

**Comment by Satoshi-Sh** [comment]
Closed by #215
