### ISSUE TITLE
Nav bar links "flickering" on hover

### ISSUE THREAD

**Issue by cherylli** [Web-Dev-Path/web-dev-path#219]
**What do we need to build or fix?**
As seen in the video, menu links "flicker" on hover on the right end of the text

https://github.com/Web-Dev-Path/web-dev-path/assets/6191116/875a5235-1e08-4579-95ef-70709e1be4e9

**Technical details**
We need to check the CSS and see if there's anything causing an infinite loop of style change on hover

**Approach suggestions**
Check styles

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**Comment by Satoshi-Sh** [comment]
Closed via #220
