### ISSUE TITLE
Next.js Category has no blog posts

### ISSUE THREAD

**Issue by Satoshi-Sh** [Web-Dev-Path/web-dev-path#225]
**Screenshot**
![Screenshot from 2024-11-18 08-04-40](https://github.com/user-attachments/assets/1822787e-dd0b-481e-9671-d93a7320d3eb)

**What do we need to build or fix?**
Remove the Next.js category or find out the reason why we don't have nextjs tagged blog posts (I believe we used to have one or two.) 

**Approach suggestions**
Solution 1: Remove the `utils/blogCategories.js` in line 4 and line 10. It will remove the empty nextjs category from the blog page.

![Screenshot from 2024-11-18 12-48-42](https://github.com/user-attachments/assets/a8083cb8-51e2-4ea8-9897-31305ca86400)

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**

- Test the section and components in many screen sizes, you can use the Inspect tool for that.
- Please test if the new changes added to the components do not affect the other instances.
- Test the feature in many browsers, such as Chrome, Firefox, Edge, and Safari (MAC).
- If there are any build problems when submitting your PR, run `yarn build` locally to solve the issues and commit the changes.
- Update the CHANGELOG.md file.

**UPDATE**
According to the [post](https://stackoverflow.com/questions/74088023/using-dev-to-api-now-only-shows-last-30-articles), Dev.to API shows up to latest 30 blog posts.  We currently have 33 blog posts. We need to research how to get all the posts or think about other solutions.

**Comment by cherylli** [comment]
https://developers.forem.com/api/v1#tag/articles/operation/getArticles
Easiest fix is just fetch more articles
![image](https://github.com/user-attachments/assets/0f4377fd-8fea-4344-975c-df34a3b03b76)
