### ISSUE TITLE
Resolve `fetchPriority` prop warning in `next/image`

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#227]
**What do we need to build or fix?**
The project is currently showing a warning related to the `fetchPriority` prop when using the `next/image` component. This warning indicates that React does not recognize `fetchPriority` as a valid DOM element attribute. It suggests a possible inconsistency between the current Next.js and React versions.

![Screenshot 2024-11-28 at 11 51 09 AM](https://github.com/user-attachments/assets/01117b9d-e1d8-4b02-8921-cd9771ef9c2f)

**Technical details**
This warning seems to occur due to an incompatibility between the current Next.js version and React. It could also relate to the usage of `fetchPriority` in the `next/image` component.

**Approach suggestions**
- Update the project to the latest stable version of Next.js and check if the warning is resolved.  
 - Test the build and ensure compatibility across all components.
 - If updating Next.js doesn't resolve the issue, consider locking React to version `18.2.0`, as suggested in [this Reddit thread](https://www.reddit.com/r/nextjs/comments/1djdso4/react_does_not_recognize_the_fetchpriority_prop/).

**Deadline**
Please keep in mind that once you assign this task to yourself, you'll need to complete it in 10 days.

**Acceptance criteria**
- [ ] Test the updated components across various screen sizes using the Inspect tool.  
- [ ] Ensure the updates to the components do not negatively affect other instances.  
- [ ] Test the feature in multiple browsers, including Chrome, Firefox, Edge, and Safari (macOS).  
- [ ] Resolve any build problems locally using `yarn build` before submitting the PR.  
- [ ] Update the `CHANGELOG.md` file to reflect the changes made.

**Comment by Satoshi-Sh** [comment]
Resolved in #228
