### ISSUE TITLE
Next stop: our web dev path platform!

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#30]
Hey dear web devs <3,

I've bought the domain webdevpath.co so that we can build a real platform in a collaborative environment! So, the next step is to start doing what we've been doing so far with real code simulating a real-world scenario. It's going to be a place where we can share our discoveries related to web development. 

Initially, I'm thinking about creating something inspired by this idea https://www.samanthaming.com/ by using [Gatsby](https://www.gatsbyjs.com/) and following the [agile methodology](https://www.infoworld.com/article/3237508/what-is-agile-methodology-modern-software-development-explained.html). And we already have a [project](https://github.com/MarianaSouza/web-dev-path/projects/1)!

![image](https://user-images.githubusercontent.com/20016897/102680064-f607a600-4169-11eb-860d-98c0ef5ec547.png)

I'm keeping our conversation on [Slack](https://join.slack.com/t/webdevpath/shared_invite/zt-je2zuuja-zlQr2_YpFP_9zuyGcKeYGg), but I just thought that would be nice to make an official announcement here :D

If you feel up to the challenge, I invite you all to take a look at Gatsby and React documentation to get ready! Feedback and ideas are MORE than welcome!

Feel free to reach out here or on Slack if you have any questions. Talk soon!

@ZahraB21 @rebecatschiedel @CarolDill @helgakern @kaileegiles 

### Steps:

- [x] Meeting in January to define main ideas for the platform (technologies/purpose/initial pages)
- [x] Initial wireframes (issue #32 )

**Comment by ZahraB21** [comment]
@MarianaSouza I'm in for sure.

**Comment by ZahraB21** [comment]
@MarianaSouza should we work on the wire frames ?

**Comment by MarianaSouza** [comment]
> @MarianaSouza should we work on the wire frames ?

That's one of the first steps for sure. Would you like to start creating a simple issue for that and linking it to our [project](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/adding-issues-and-pull-requests-to-a-project-board#:~:text=On%20the%20right%20side%20of,the%20issue%20or%20pull%20request.)?

**Comment by ZahraB21** [comment]
> > @MarianaSouza should we work on the wire frames ?
> 
> That's one of the first steps for sure, @ZahraB21 . Would you like to start creating a simple issue for that and linking it to our [project](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/adding-issues-and-pull-requests-to-a-project-board#:~:text=On%20the%20right%20side%20of,the%20issue%20or%20pull%20request.)?

Yes, I will do it on Monday.

**Comment by ZahraB21** [comment]
Hi @MarianaSouza, 
I have added an issue and linked it to the project.

**Comment by MarianaSouza** [comment]
> Hi @MarianaSouza,
> I have added an issue and linked it to the project.

Cool, @ZahraB21, thanks ! Can you go to the projects section there (attached) and link it to the project? Also, could you please add "investigation" and "Help wanted" labels and assign it to everyone so that we're all notified?

I guess I'd also add this resource there too: https://gomockingbird.com/home

![image](https://user-images.githubusercontent.com/20016897/102819285-0ac18500-4388-11eb-9075-4147f87c52c0.png)

**Comment by ZahraB21** [comment]
> > Hi @MarianaSouza,
> > I have added an issue and linked it to the project.
> 
> Cool, @ZahraB21, thanks ! Can you go to the projects section there (attached) and link it to the project? Also, could you please add "investigation" and "Help wanted" labels and assign it to everyone so that we're all notified?
> 
> I guess I'd also add this resource there too: https://gomockingbird.com/home
> 
> ![image](https://user-images.githubusercontent.com/20016897/102819285-0ac18500-4388-11eb-9075-4147f87c52c0.png)

@MarianaSouza I have done what you have asked. :)

**Comment by MarianaSouza** [comment]
> > > Hi @MarianaSouza,
> > > I have added an issue and linked it to the project.
> > 
> > 
> > Cool, @ZahraB21, thanks ! Can you go to the projects section there (attached) and link it to the project? Also, could you please add "investigation" and "Help wanted" labels and assign it to everyone so that we're all notified?
> > I guess I'd also add this resource there too: https://gomockingbird.com/home
> > ![image](https://user-images.githubusercontent.com/20016897/102819285-0ac18500-4388-11eb-9075-4147f87c52c0.png)
> 
> @MarianaSouza I have done what you have asked. :)

Hey @ZahraB21 , the labels are well set, but you still need to connect the issue with the project as attached:

![tempsnip](https://user-images.githubusercontent.com/20016897/103039160-fb2b7300-4524-11eb-83c1-ff24e8edf8e1.png)

Please let me know if that makes sense. Thanks!

**Comment by ZahraB21** [comment]
> > > > Hi @MarianaSouza,
> > > > I have added an issue and linked it to the project.
> > > 
> > > 
> > > Cool, @ZahraB21, thanks ! Can you go to the projects section there (attached) and link it to the project? Also, could you please add "investigation" and "Help wanted" labels and assign it to everyone so that we're all notified?
> > > I guess I'd also add this resource there too: https://gomockingbird.com/home
> > > ![image](https://user-images.githubusercontent.com/20016897/102819285-0ac18500-4388-11eb-9075-4147f87c52c0.png)
> > 
> > 
> > @MarianaSouza I have done what you have asked. :)
> 
> Hey @ZahraB21 , the labels are well set, but you still need to connect the issue with the project as attached:
> 
> ![tempsnip](https://user-images.githubusercontent.com/20016897/103039160-fb2b7300-4524-11eb-83c1-ff24e8edf8e1.png)
> 
> Please let me know if that makes sense. Thanks!

Hi @MarianaSouza, 
I got it. It is connected to the project. Thank you.
