### ISSUE TITLE
Create the wireframes for our webdevpath.co

### ISSUE THREAD

**Issue by ZahraB21** [Web-Dev-Path/web-dev-path#32]
The first step in creating out website is to have wireframes. This would allow us to understand the structure of our site.  

We can use [MockingBird](https://gomockingbird.com/home) for the wireframes.

**Comment by rebecatschiedel** [comment]
Hello, ladies! 
Here are the wireframes that we talked about:
![2-Blog](https://user-images.githubusercontent.com/61192101/117097649-0f784b80-ad21-11eb-8efc-f58a2d34d9c3.png)
![3-Contact Us](https://user-images.githubusercontent.com/61192101/117097653-1010e200-ad21-11eb-8686-46ed6164d5eb.png)
![4-About Us](https://user-images.githubusercontent.com/61192101/117097654-10a97880-ad21-11eb-9b43-99e1d231ec96.png)
![1-Home](https://user-images.githubusercontent.com/61192101/117097658-11420f00-ad21-11eb-86d1-b8266d679598.png)

**Comment by MarianaSouza** [comment]
Thanks, @rebecatschiedel !
Do you ladies think we need the mobile versions or we can just agree we're stacking everything on screens < 768px ?
