### ISSUE TITLE
Typography and color palette

### ISSUE THREAD

**Issue by rebecatschiedel** [Web-Dev-Path/web-dev-path#34]
Hey web devs, 

Now that we have our wireframe, #32, it is time to start talking about color and typography.

As @MarianaSouza said on our slack group, we can think of:

-  **Typography**
2 fonts ( 1 primary and 1 secondary )
-  **Color Palette** 
3-4 colors, 2-3 bases and 1-2 accents
[Coolors](https://coolors.co/)
[Color hunt](https://colorhunt.co/)

Let's make it beautiful!! =)

**Comment by MarianaSouza** [comment]
Hey web devs! Just to have it registered here:
We have decided to use [Roboto](https://fonts.google.com/specimen/Roboto) and [Oswald](https://fonts.google.com/specimen/Oswald) as our family fonts and we're still deciding between two color palettes:

1. green/red/gold  -> https://coolors.co/ffffff-efdbbd-40c9b9-038c81-b20614-2b2a29

2. /greyyellow/blue -> https://coolors.co/ffffff-e5e5e5-ffc72c-4097db-2a638e-142f40
