### ISSUE TITLE
Branding Process Report

### ISSUE THREAD

**Issue by mariana-caldas** [Web-Dev-Path/web-dev-path#62]
Here, we're reporting all the branding processes by considering points, such as project conceptual approach, core values, initial logo, type font, and colors concept.

 **Used tooling and how the design process happened** 
The project was done on [Figma](https://www.figma.com/file/Fp0lLB5OWZLJseTs2svGbg/?node-id=26%3A2), Illustrator, and [InVision](https://projects.invisionapp.com/boards/7N432V0KUQB/) through a sharing project where both designers worked together and can be accessed through their links.

**Besides the tooling, how does the collaboration happen between the design team?** 
Zoom meetings and Slack conversations, detailed below.

**How the ideas were presented to the team leader and to the developers?**
 The ideas were presented by adding the process to the Branding Process Report on Github and by following up with the comments and suggestions provided by the team.

---

# Our Branding Process

## Web Dev Path Concept
The Web Dev Path is a team of professional developers project that aims to provide a comprehensive path for people who seek to begin their web development journey. To do so, we're building a Next.js platform that will be a place to share ideas about web development and where Non-Profit Organizations can get help for their web products by sharing their project and needs and getting connected to volunteer junior web developers.

## Core Values
Connection
Supportive [environment]
Energetic
Respect
Personal Development Cooperation Learning Patience Team Work
Knowledge
Sharing

## Branding Ideation | Keywords
collaborative
friendly
approachable
supportive
growth-oriented
energetic/young
professional
credible

### Color Psychology
<img src="https://user-images.githubusercontent.com/61192101/144152709-1ab1ab9f-851c-4a4a-9a63-8073be56b6ec.jpg" width="600" />

#### Palette 01
<img src="https://user-images.githubusercontent.com/61192101/144152708-17298eae-0337-47b5-a501-c749da483b90.jpg" width="300" />

#### Palette 02
<img src="https://user-images.githubusercontent.com/61192101/144152704-b0698974-5dcb-4153-a78c-fc89d986bac7.jpg" width="300" />

#### Palette 03
<img src="https://user-images.githubusercontent.com/61192101/144152707-57175f39-8943-4cf2-be81-af5e7c786dbc.jpg" width="300" />

### Concept 01
Like tree roots, knowledge is distributed through streams at Web Dev Path. This concept is about that network and path suggested through the use of curly brackets - an element intended to link that concept to the world of coding. 

#### Palette 01

![WDP_logo__5_conceptA 1](https://user-images.githubusercontent.com/61192101/144152954-e176c498-6ca6-41da-ab69-0d7650aec223.jpg)

#### Palette 02

![WDP_logo__7A 1](https://user-images.githubusercontent.com/61192101/144152959-5ba95451-acd6-4028-b20e-5269beb90f23.jpg)

### Concept 02
This concept explores the curly brackets to create a "path" - a little more abstract. It also suggests two people facing each other "exchanging"[ideas].

#### Palette 01

![WDP_logo__5_conceptC 1](https://user-images.githubusercontent.com/61192101/144152997-c33ebb11-55b8-4e80-adda-5f537dfaee15.jpg)

#### Palette 02

![WDP_logo__7C 1](https://user-images.githubusercontent.com/61192101/144152999-0c4fcff7-e888-4254-9ed0-4bf73f00e67c.jpg)

### Concept 02-B
Same as concept 02, in an alternative arrangement.

#### Palette 01

![WDP_logo__5_conceptB 1](https://user-images.githubusercontent.com/61192101/144153034-373196b2-5274-49ea-9d17-89ed4dea1f2f.jpg)

#### Palette 02

![WDP_logo__7B 1](https://user-images.githubusercontent.com/61192101/144153035-7d262dad-7dc5-4605-ad22-0ea35a0be1e4.jpg)

### Concept 03
"Path" is explored in this concept as an ever-unfolding spiral - resembling the knowledge acquisition journey.

#### Palette 01

![WDP_logo__7_background 1](https://user-images.githubusercontent.com/61192101/144153063-3521ac44-768d-42f0-910c-424fbe9a31ff.jpg)

#### Palette 02

![WDP_logo__7D 1](https://user-images.githubusercontent.com/61192101/144153067-c6d3c05d-62d2-49bc-bc6a-9b71c6222492.jpg)

### Concept 04
The logo is ideate as a road, followed by the words in different positions as an advance in the road, representing the progress that the user will experience.

#### Palette 01

![Frame 1](https://user-images.githubusercontent.com/61192101/144153086-0366c305-875e-4547-a10f-a269f4262dd6.jpg)

#### Palette 02

![Frame 2](https://user-images.githubusercontent.com/61192101/144153083-c18f8d7c-748b-4820-bd6e-b765d38cb949.jpg)

## Typography
**This is an initial exploration of typography and the possibility of different font combinations.**

<img width="1165" alt="Group 23" src="https://user-images.githubusercontent.com/61192101/144152655-b0efaee8-a876-49aa-923b-9478fbf6e18e.png">

### Typefaces used: Inconsolata + Assistant
![WDP_logo__9c](https://user-images.githubusercontent.com/85603056/145143341-8cca4fce-f208-464f-ba87-f9ce9d46ddab.jpg)

### Typefaces used: Open Sans + Lato
![WDP_logo__9](https://user-images.githubusercontent.com/85603056/145138953-ffce389a-1719-4c92-91fa-6e79116884da.jpg)

### Typefaces used: Open Sans + Assistant
![WDP_logo__9-02](https://user-images.githubusercontent.com/85603056/145142832-51e7a521-1d41-4289-9b2c-467f1cae7262.png)

## Branding look and feel*
This is a sample of what is being envisioned for the branding look in terms of ELEMENTS and COLOUR. Youthful, modern, having coding elements in a way to portray "friendly".   
(PS: This is NOT intended to represent UI. This is meant to convey an early-stage branding vision for feedback/discussion). Typography, colors, and approach are all up for debate.

#### Palette 01
![WDP_logo__9-02](https://user-images.githubusercontent.com/85603056/145143506-00bc2e24-66b5-459f-8e92-ffbf92810d5e.png)

#### Palette 02
![WDP_logo__9-03](https://user-images.githubusercontent.com/85603056/145143529-59066d89-db39-4c8e-b71d-60963f1f698b.png)

#### Palette 03
![WDP_logo__9-01](https://user-images.githubusercontent.com/85603056/145143554-37b41aaf-9649-4309-8ade-28617dc6f8a4.png)

# Comment below your answers to the following:
- Do all the core values resonate with your vision about this project?
- What color palette best represents Web Dev Path's core values?
- What are your top 2 logo concepts that best represent Web Dev Path project? What do you like about them?
- What do you think about the overall branding concept? We will appreciate any comments, suggestions, or questions.

## Meetings

**Dates**: 
- 01/11, 18/11, 23/11 (+- 1hr duration)
- 29/11

**Topics discussed:**
- 01/11: Discussion on core requirements for web dev path's website with @MarianaSouza
- 18/11: Logo conceptualization (sketching, ideation) [preliminary logo+branding 1/3]
- 23/11: Logo: first concepts (images attached) + selection of colours [preliminary logo+branding 2/3]
- Upcoming meeting on 29/11: Definition of branding color palette, typography, brand's look, and feel + final selection of logo concepts for proposal to be presented to the team on Nov 30th. [preliminary logo+branding 3/3]
Release of logo and branding concepts for feedback: Nov 30th, 2021

**Comment by jomaira-rgb** [comment]
Design meetings are taking place via Zoom between @rebecatschiedel and @jomaira-rgb 
Dates: 01/11, 18/11, 23/11 (+- 1hr duration)
Topics discussed:
- Meeting on 01/11: Discussion on core requirements for web dev path's website with @MarianaSouza 
- Meeting on 18/11: Logo conceptualization (sketching, ideation) _[preliminary logo+branding 1/3]_
- Meeting on 23/11: Logo: first concepts (images attached) + selection of colours _[preliminary logo+branding 2/3]_
- Upcoming meeting on 29/11: Definition of branding colour palette, typography, brand's look and feel + final selection of logo concepts for proposal to be presented to the team on Nov 30th. [preliminary logo+branding 3/3]

Release of logo and branding concepts for feedback: Nov 30th, 2021

**Comment by MarianaSouza** [comment]
_Do all the core values resonate with your vision about this project?_

I think so. I think they reflect the collaboration and energy the project represents.

_What color palette best represents Web Dev Path's core values?_

My favorites are numbers 1 and 2

_What are your top 2 logo concepts that best represent Web Dev Path project? What do you like about them?_

I tend to think concepts 1 and 2, and especially the number 2, are in tune with our purpose.

_What do you think about the overall branding concept?_ 

I like how simple and energetic it feels. I can see us building the website with a minimalistic approach that will be, at the same time, rich in color to represent how approachable we want to be for the tech community.

Thanks so much for your amazing work so far @rebecatschiedel and @jomaira-rgb 😍

**Comment by jomaira-rgb** [comment]
Thank you for the feedback @MarianaSouza   _"I can see us building the website with a minimalistic approach that will be, at the same time, rich in color to represent how approachable we want to be for the tech community."_ I think we are on track to achieve that for sure. :) Thank you

**Comment by ZahraB21** [comment]
Hi guys,
First of all thank you for all your time and efforts in presenting your ideas. They all look wonderful. 

I am a bit busy these days so I'll keep it short. In terms of concept, I like concept 01 cause in web dev path, you need to start learning from the basics and then go deep down and learn other things and it looks like a DOM tree. In terms of palette, I like the second palette, its motivating and warm and formal too. In terms of typeface, I liked the open sans and lato more than the others. 

Overall, I would say for the general branding and look and feel of the site, palette 2 would be my selection. 

Thank you and great job again.

**Comment by MarianaSouza** [comment]
Hi team,
Quick update on the concepts for logo, branding, and typography that got chosen for Web Dev Path's website.

**Logo::**
![WDP_logo__5_conceptA](https://user-images.githubusercontent.com/85603056/147304178-e33bed5e-7dad-4024-89c6-11ecad9e3986.jpg)

**Branding colours::**
<img width="379" alt="colour_palette" src="https://user-images.githubusercontent.com/85603056/147305001-f67012ea-20c9-4136-9937-a69607b013a5.PNG">

**Typography + Feel::**
Open Sans + Assistant
![WDP_logo__9-02](https://user-images.githubusercontent.com/85603056/147304979-19990715-cc2b-4fc0-8ed4-19d38a5e04aa.png)

Up next: UI design for homepage followed by Blog and About + Contact pages 
Expected delivery: January 14th or sooner.

**Comment by jomaira-rgb** [comment]
Hello, just to update look and feel featuring chosen colours :)
![WDP_logo__10_ok](https://user-images.githubusercontent.com/85603056/147602517-7c26831b-b3bc-4a04-8244-c7e655567f02.png)

Happy new year!
